### ISSUE TITLE
Design Struktur Split

### ISSUE THREAD

**Issue by Wab00se** [FachinformatikerLabs/SmartFitAI#30]
Um eine besser Übersicht zu schaffen, wird die SmartFit_Gui.kv (welche bisher alle Views enthält) in "einzelne" kv Datein gesplittet.

**Comment by nyxb** [comment]
Wird diese denn dann auch gelöscht?

**Comment by nyxb** [comment]
> Um eine besser Übersicht zu schaffen, wird die SmartFit_Gui.kv (welche bisher alle Views enthält) in "einzelne" kv Datein gesplittet.


Wird diese denn dann auch gelöscht?

**Comment by Wab00se** [comment]
Ja die kann weg. Erfüllt keinen Zweck mehr. Die Views werden jetzt über den Builder geladen und über den WindowManager verwaltet.

**Comment by nyxb** [comment]
Ok die muss dann noch nachträglich einfach gelöscht werden, habe das jetzt nicht mehr vor dem merge gemacht.
