### ISSUE TITLE
Erstellen der SQL DB mit Rezepten

### ISSUE THREAD

**Issue by ThreshOffTheBoat** [FachinformatikerLabs/SmartFitAI#60]
In Supabase  eine  DB mit 8-10 Rezepten und dessen Allergene erstellen

**Comment by nyxb** [comment]
Sehr gut 👍

**Comment by ThreshOffTheBoat** [comment]
Datenbank in PostgresSQL in Supabase erstellt. 9 rezepte drin, voll normalisiert. Wird noch weiter erweitert.

Datenbank ArchiteKtur wie im Bild:

![smartfit sql architecture.PNG](https://volta.s3.fr-par.scw.cloud/smartfit_sql_architecture_e6fcf410f3.PNG)
