### ISSUE TITLE
Rezepte auf Suche anklicken und anzeigen

### ISSUE THREAD

**Issue by nyxb** [FachinformatikerLabs/SmartFitAI#71]
Alle Zutaten des Rezept anzeigen und die Instruction anzeigen.

**Comment by ThreshOffTheBoat** [comment]
Suche funktioniert als Pop-Up, so dass der User sich das Rezept ansehen kann und das Fenster wieder schließen falls er sich nochmal ein anderes Rezept ansehen kann.
Sieht noch nicht einheitlich aus mit der Dashboard.
